[package]
name = "matasano"
version = "0.1.0"
authors = ["Adolfo <adolfo@infi.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.24"
rand = "0.7.2"
